### ISSUE TITLE
Doesn't seem to work with fork-ts-checker-webpack-plugin 1.0.0

### ISSUE THREAD

**Issue by akonyer** [johnnyreilly/fork-ts-checker-notifier-webpack-plugin#14]
I'm sure you're aware, but fork-ts-checker-webpack-plugin just released v 1.0.0

This doesn't seem to work anymore. Just thought I'd give you a heads up.

**Comment by johnnyreilly** [comment]
If you use the alpha you should be good - I'll try and ship the real deal shortly!
