### ISSUE TITLE
index.d.ts not included in NPM

### ISSUE THREAD

**Issue by cdeutsch** [johnnyreilly/fork-ts-checker-notifier-webpack-plugin#19]
The `index.d.ts` isn't being included in the published NPM.

**Comment by johnnyreilly** [comment]
Ah - we should remove this I think: https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin/blob/cafba0be10b8151ebf4b45d189129b85357359bf/.npmignore#L3

**Comment by cdeutsch** [comment]
That would probably do it 👍

**Comment by johnnyreilly** [comment]
Cool - want to submit a PR? I'm away on my hols right now but if I've as PR waiting I should be able to ship it quickly upon my return
