### ISSUE TITLE
Prop excludeWarnings: true does not work.

### ISSUE THREAD

**Issue by Stralos** [johnnyreilly/fork-ts-checker-notifier-webpack-plugin#21]
The property `excludeWarnings` does not work, and I receive a notification that there is an error even when it is set to true.

Looking at the code base the problem is at lines 49-63. Printing out an error happens before checking if the prop has been set. It seems there is no way to disable the error notification.

```
    if (firstError) {
      this.lastBuildSucceeded = false;

      return {
        title: util.format(
          '%s%s',
          this.titlePrefix,
          'Error in ' + path.basename(firstError.file || '')
        ),
        message: firstError.content,
        icon: path.join(__dirname, 'images/error.png')
      };
    }

    if (firstWarning && !this.options.excludeWarnings) {
```

**Comment by johnnyreilly** [comment]
Thanks for looking into this! Do you fancy submitting a PR?

**Comment by Stralos** [comment]
Give me a day or two.
