### ISSUE TITLE
SnoreToast's notifications work randomly

### ISSUE THREAD

**Issue by Wojtasik** [johnnyreilly/fork-ts-checker-notifier-webpack-plugin#28]
### Expected Behaviour
On Windows 10 Pro, I'd expect to receive all the error notification sent by ForkTsCheckerNotifierWebpackPlugin.

### Actual Behaviour
On Windows 10 Pro, I receive notifications randomly. Most of the times, they are not visible.

### Steps to Reproduce the Problem
- using PowerShell, go to `vendor/snoreToast`
- run `.\SnoreToast.exe -m 'test' -t 'title'`
- no notification visible

I am using:
Microsoft Windows
Version 1903 (OS Build 18362.476)

On the other hand, I tried snoretoast@0.7. Running it from command line worked 10 times out of 10.

SnoreToast.exe version used in this repo: 0.5.2.
Maybe it would be enough to update snoretoast.exe to the newest version?

**Comment by johnnyreilly** [comment]
Do you want to send a PR?

**Comment by Wojtasik** [comment]
@johnnyreilly done. Please take a look on #29 

The newest version of snoretoast (0.7.0) comes with the newest version of node-notifier (6.0.0).
