### ISSUE TITLE
Upgrade node-notifier or make it a peer dependency

### ISSUE THREAD

**Issue by hisuwh** [johnnyreilly/fork-ts-checker-notifier-webpack-plugin#52]
### Expected Behaviour
`node-notifier` needs to be updated to 8.0.1 or later to address: https://github.com/advisories/GHSA-5fw9-fq32-wv5p
Or it could probably be made a peer dependency.

### Actual Behaviour
Depends on version less than 8.0.1

### Steps to Reproduce the Problem
run `npm audit` in package dependent on `fork-ts-checker-notifier-webpack-plugin`

**Comment by johnnyreilly** [comment]
If you'd like to submit a PR I'll take a look

**Comment by hisuwh** [comment]
@johnnyreilly done.
